version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - fastzero_app
    environment:
      - NODE_ENV=production
      - URL_BASE=http://172.16.238.11:8002
      - NEXTAUTH_URL=http://172.16.238.9:3000
      - NEXTAUTH_BACKEND_URL=http://172.16.238.11:8002
      - AUTH_SECRET=o2H0yYZj6!BncIdOvA9Tm7bqsCea1RU#VDl4wh8zXNx^EKS
      - NEXTAUTH_SECRET=d339c41174400919c42332923ace4e5d34a3ec235f02460a84a92b1659123333526618d6aec011c6c755615b4d2e500e419b53901d07ff07277954a9d2d04389f7b4dc2015454188135fe352c03fc3ae43713b621f3f40dfe69434559d0eaa1352a4e05adf9c716048320789e6df456121fca6c2dbf9fa12cd06bf6805c4d0891f6e5bc529603afe7b8244743ec8880b0bf0d07e5692a7ac6f8301c7bf63722e947141e1432cb9c29216762b48026bf1be2c289589490889b98bcf355934f64dac031bb867b4de760be5af916aca95c3ddca865776217e563c93b526d25e65612037b0a2fcb62bb985e4e5dc9320261f17d56f6f5144c2c1791f32b441b8ef40
    networks:
      backend:
        ipv4_address: 172.16.238.9
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend
    links:
      - frontend
    networks:
      backend:
        ipv4_address: 172.16.238.8

  database:
    image: postgres:16.4
    networks:
      backend:
        ipv4_address: 172.16.238.10
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5433:5432"
    command: ["postgres", "-c", "timezone=America/Sao_Paulo"]

  fastzero_app:
    image: fastzero_app
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8002:8002"
    networks:
      backend:
        ipv4_address: 172.16.238.11
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@172.16.238.10:5432/app_db

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

volumes:
  pgdata: