"""cria constraint role_permission

Revision ID: 10ce054269b9
Revises: f82a36a40982
Create Date: 2024-08-04 14:19:30.057756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ce054269b9'
down_revision: Union[str, None] = 'f82a36a40982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_role_id_permission_id', 'role_permissions', ['role_id', 'permission_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_role_id_permission_id', 'role_permissions', type_='unique')
    # ### end Alembic commands ###
