"""update otp user tabela user

Revision ID: 3197a1279fe6
Revises: 365134451969
Create Date: 2024-08-12 14:25:56.716800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3197a1279fe6'
down_revision: Union[str, None] = '365134451969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_auth_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_auth_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
