"""tabelas cadastro de pessoas

Revision ID: 6aebf6a57a89
Revises: e6bf05aab84d
Create Date: 2024-09-23 09:46:49.548439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aebf6a57a89'
down_revision: Union[str, None] = 'e6bf05aab84d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bairro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio_id', 'nome', name='uix_municipio_id_nome')
    )
    op.create_table('cep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('bairro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bairro_id'], ['bairro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cep', 'bairro_id', name='uix_cep_bairro_id')
    )
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=14), nullable=False),
    sa.Column('rua', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('complemento', sa.String(), nullable=False),
    sa.Column('cep_id', sa.Integer(), nullable=False),
    sa.Column('rg', sa.String(length=11), nullable=True),
    sa.Column('ie', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cep_id'], ['cep.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_table('telefone_pessoa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Enum('p', 'c', 'o', name='tipoendereco'), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo', 'telefone', 'pessoa_id', name='uix_tipo_telefone_pessoa_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telefone_pessoa')
    op.drop_table('pessoa')
    op.drop_table('cep')
    op.drop_table('bairro')
    # ### end Alembic commands ###
