"""config otp

Revision ID: 806734a5032b
Revises: 3d331f2afb24
Create Date: 2024-08-12 12:55:34.544845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '806734a5032b'
down_revision: Union[str, None] = '3d331f2afb24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'module', ['title'])
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('otp_base32', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_auth_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('login_otp_used', sa.Boolean(), nullable=False))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'login_otp_used')
    op.drop_column('users', 'otp_created_at')
    op.drop_column('users', 'otp_auth_url')
    op.drop_column('users', 'otp_base32')
    op.drop_column('users', 'full_name')
    op.drop_constraint(None, 'module', type_='unique')
    # ### end Alembic commands ###
