"""adiciona campo description na tabela permission

Revision ID: e951631ed5bb
Revises: 9808874c9e67
Create Date: 2024-08-03 14:12:45.092495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e951631ed5bb'
down_revision: Union[str, None] = '9808874c9e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('permissions', 'description')
    # ### end Alembic commands ###
