"""alter tabela user

Revision ID: f0da87eb25d3
Revises: 4e44b269ba39
Create Date: 2024-08-30 12:43:48.943450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0da87eb25d3'
down_revision: Union[str, None] = '4e44b269ba39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('negociacao_credito', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('negociacao_credito_id_seq'::regclass)"))
    op.alter_column('negociacao_credito', 'data_pri_parc',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('negociacao_credito', 'data_ult_parc',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_unique_constraint('unique_numero_type_negociacao', 'parcelamento_negociacao', ['numero_parcela', 'type', 'negociacao_id'])
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_constraint('unique_numero_type_negociacao', 'parcelamento_negociacao', type_='unique')
    op.alter_column('negociacao_credito', 'data_ult_parc',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('negociacao_credito', 'data_pri_parc',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('negociacao_credito', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('negociacao_credito_id_seq'::regclass)"))
    # ### end Alembic commands ###
