"""cria negociacao

Revision ID: f1675151ead5
Revises: 8eacd008326a
Create Date: 2024-08-13 22:18:53.498694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1675151ead5'
down_revision: Union[str, None] = '8eacd008326a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negociacao_credito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processo', sa.String(length=200), nullable=True),
    sa.Column('executado', sa.String(length=200), nullable=False),
    sa.Column('contrato', sa.String(length=100), nullable=True),
    sa.Column('val_devido', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('val_desconto', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('val_neg', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('data_pri_parc', sa.Date(), nullable=True),
    sa.Column('data_ult_parc', sa.Date(), nullable=True),
    sa.Column('val_entrada', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('qtd_parc_ent', sa.Integer(), nullable=True),
    sa.Column('data_pri_parc_entr', sa.Date(), nullable=True),
    sa.Column('data_ult_parc_entr', sa.Date(), nullable=True),
    sa.Column('obs_val_neg', sa.String(length=100), nullable=True),
    sa.Column('is_term_ex_jud', sa.Boolean(), nullable=False),
    sa.Column('is_hom_ext_jud', sa.Boolean(), nullable=False),
    sa.Column('qtd', sa.Integer(), nullable=False),
    sa.Column('taxa_mes', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('val_parc', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('is_cal_parc_mensal', sa.Boolean(), nullable=False),
    sa.Column('is_cal_parc_entrada', sa.Boolean(), nullable=False),
    sa.Column('is_descumprido', sa.Boolean(), nullable=False),
    sa.Column('is_liquidado', sa.Boolean(), nullable=False),
    sa.Column('is_retorno_execucao', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processo', 'executado', 'contrato', name='unique_processo_executado_contrato')
    )
    op.create_table('parcelamento_negociacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negociacao_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('val_parcela', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('val_pago', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('obs_val_pago', sa.String(length=100), nullable=True),
    sa.Column('data_pgto', sa.Date(), nullable=True),
    sa.Column('type', sa.Integer(), default=1),
    sa.Column('numero_parcela', sa.Integer(), nullable=False),
    sa.Column('is_pg', sa.Boolean(), nullable=False),
    sa.Column('is_val_juros', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['negociacao_id'], ['negociacao_credito.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcelamento_negociacao')
    op.drop_table('negociacao_credito')
    # ### end Alembic commands ###
