"""corrije estrutura tabela permission

Revision ID: f22425ddf649
Revises: e951631ed5bb
Create Date: 2024-08-03 18:20:10.868123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f22425ddf649'
down_revision: Union[str, None] = 'e951631ed5bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission_module')
    op.add_column('permissions', sa.Column('module_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uix_name_modules', 'permissions', ['name', 'module_id'])
    op.create_foreign_key(None, 'permissions', 'module', ['module_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint('uix_name_modules', 'permissions', type_='unique')
    op.drop_column('permissions', 'module_id')
    op.create_table('permission_module',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], name='permission_module_module_id_fkey'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='permission_module_permission_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='permission_module_pkey')
    )
    # ### end Alembic commands ###
