"""corrige estrutura tabela permission

Revision ID: f82a36a40982
Revises: f22425ddf649
Create Date: 2024-08-03 18:23:12.988343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82a36a40982'
down_revision: Union[str, None] = 'f22425ddf649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_permissions_name', table_name='permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_permissions_name', 'permissions', ['name'], unique=True)
    # ### end Alembic commands ###
